### ISSUE TITLE
FR: search by name?

### ISSUE THREAD

**Issue by n8henrie** [hsjobeki/noogle#2]
Being new to nix, I'm so grateful to have a way to search by function signature and have already found this very useful. Thank you!

I was surprised that searching by fully qualified function name didn't work, for example I wanted to look at `builtins.elem`. It shows up if I search for `a -> [b] -> bool`, but searching for `elem` gives me 7 pages of results and `builtins.elem` gives 0 results. While I don't haskell, if keeping similarity to Hoogle is of concern, searching for `elem` seems to yield expected results.

If there's the possibility of adding a feature to search by function name in addition to signature I think it would be helpful. Thank again for providing an already very useful site!

**Comment by hsjobeki** [comment]
Adding that feature would be an easy fix. 
Will work on the search algorithms that will show more relevant entries first. 
I see two points here:
1. Allow searches by fully Qualified names
2. Sort entries by relevance 

i think i’ll add those features soon after the Christmas days

**Comment by n8henrie** [comment]
Awesome, thanks!
